package platform

// Task 058 storage: the v1 → v2 migration, cursor/evidence consistency, and
// the atomicity the retry protocol depends on.
//
// These live inside the package because they need direct SQL. The migration
// tests in particular need to build a database this code cannot produce any
// more, which is the whole point: a fixture generated by calling the current
// schema creation and rewriting the version number would prove nothing about
// migrating a real task 057 database.

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"math"
	"path/filepath"
	"sync"
	"testing"
	"time"

	trustvian "github.com/trustvian/trustvian"
)

// schemaV1Statements is task 057's schema, pinned.
//
// Deliberately a literal copy rather than a call into the current schema
// builder. If schema v2's definition drifts, this fixture must not drift with
// it — it represents a database that already exists on somebody's disk, and
// migrating *that* is what these tests check.
func schemaV1Statements() []string {
	return []string{
		`CREATE TABLE platform_schema_version (
			id      INTEGER PRIMARY KEY CHECK (id = 1),
			version INTEGER NOT NULL
		)`,
		`CREATE TABLE platform_projects (
			id   TEXT PRIMARY KEY,
			name TEXT NOT NULL
		)`,
		`CREATE TABLE platform_agents (
			id         TEXT PRIMARY KEY,
			project_id TEXT NOT NULL REFERENCES platform_projects(id),
			name       TEXT NOT NULL
		)`,
		`CREATE TABLE platform_candidates (
			id              TEXT PRIMARY KEY,
			agent_id        TEXT NOT NULL REFERENCES platform_agents(id),
			label           TEXT NOT NULL,
			source_ref      TEXT NOT NULL,
			artifact_digest TEXT NOT NULL,
			model           TEXT NOT NULL,
			toolset_digest  TEXT NOT NULL,
			config_digest   TEXT NOT NULL
		)`,
		`CREATE TABLE platform_evaluation_runs (
			id                 TEXT PRIMARY KEY,
			candidate_id       TEXT NOT NULL REFERENCES platform_candidates(id),
			environment        TEXT NOT NULL,
			behavioral_profile TEXT NOT NULL,
			status             TEXT NOT NULL,
			created_at         TEXT NOT NULL,
			started_at         TEXT,
			finished_at        TEXT,
			failure_reason     TEXT NOT NULL
		)`,
		`CREATE TABLE platform_evaluation_aggregates (
			run_id             TEXT PRIMARY KEY REFERENCES platform_evaluation_runs(id),
			candidate_id       TEXT NOT NULL,
			environment        TEXT NOT NULL,
			behavioral_profile TEXT NOT NULL,
			record_count      TEXT NOT NULL,
			first_observed_at TEXT,
			last_observed_at  TEXT,
			decision_allow            TEXT NOT NULL,
			decision_observe_only     TEXT NOT NULL,
			decision_alert            TEXT NOT NULL,
			decision_challenge        TEXT NOT NULL,
			decision_require_approval TEXT NOT NULL,
			decision_block            TEXT NOT NULL,
			risk_low      TEXT NOT NULL,
			risk_medium   TEXT NOT NULL,
			risk_high     TEXT NOT NULL,
			risk_critical TEXT NOT NULL,
			approval_unspecified  TEXT NOT NULL,
			approval_not_required TEXT NOT NULL,
			approval_required     TEXT NOT NULL,
			approval_approved     TEXT NOT NULL,
			approval_denied       TEXT NOT NULL,
			policy_matched_rule    TEXT NOT NULL,
			policy_matched_default TEXT NOT NULL,
			identity_confidence_count TEXT NOT NULL,
			identity_confidence_sum   REAL NOT NULL,
			identity_confidence_min   REAL NOT NULL,
			identity_confidence_max   REAL NOT NULL,
			anomaly_score_count TEXT NOT NULL,
			anomaly_score_sum   REAL NOT NULL,
			anomaly_score_min   REAL NOT NULL,
			anomaly_score_max   REAL NOT NULL,
			anomaly_confidence_count TEXT NOT NULL,
			anomaly_confidence_sum   REAL NOT NULL,
			anomaly_confidence_min   REAL NOT NULL,
			anomaly_confidence_max   REAL NOT NULL,
			trust_score_count TEXT NOT NULL,
			trust_score_sum   REAL NOT NULL,
			trust_score_min   REAL NOT NULL,
			trust_score_max   REAL NOT NULL,
			context_risk_count TEXT NOT NULL,
			context_risk_sum   REAL NOT NULL,
			context_risk_min   REAL NOT NULL,
			context_risk_max   REAL NOT NULL
		)`,
		`CREATE TABLE platform_behavior_snapshots (
			run_id             TEXT PRIMARY KEY REFERENCES platform_evaluation_runs(id),
			candidate_id       TEXT NOT NULL,
			environment        TEXT NOT NULL,
			behavioral_profile TEXT NOT NULL,
			observation_count  TEXT NOT NULL,
			distinct_count     INTEGER NOT NULL,
			complete           INTEGER NOT NULL
		)`,
		`CREATE TABLE platform_behavior_entries (
			run_id             TEXT NOT NULL REFERENCES platform_behavior_snapshots(run_id),
			fingerprint_id     TEXT NOT NULL,
			actor_type         TEXT NOT NULL,
			operation_category TEXT NOT NULL,
			operation_name     TEXT NOT NULL,
			target_name        TEXT NOT NULL,
			target_category    TEXT NOT NULL,
			environment        TEXT NOT NULL,
			observations       TEXT NOT NULL,
			PRIMARY KEY (run_id, fingerprint_id)
		)`,
	}
}

// writeSchemaV1 creates a structurally real task 057 database.
func writeSchemaV1(t *testing.T, path string) *sql.DB {
	t.Helper()
	db, err := sql.Open("sqlite", path+"?_pragma=foreign_keys(1)")
	if err != nil {
		t.Fatalf("sql.Open() error = %v", err)
	}
	db.SetMaxOpenConns(1)
	for _, statement := range schemaV1Statements() {
		if _, err := db.ExecContext(context.Background(), statement); err != nil {
			t.Fatalf("create v1 schema: %v", err)
		}
	}
	if _, err := db.ExecContext(context.Background(),
		`INSERT INTO platform_schema_version (id, version) VALUES (1, 1)`); err != nil {
		t.Fatalf("stamp v1: %v", err)
	}
	return db
}

// seedV1Content fills a v1 database with the hierarchy and one run's evidence.
func seedV1Content(t *testing.T, db *sql.DB, runID string, records uint64) {
	t.Helper()
	ctx := context.Background()
	epoch := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC).Format(time.RFC3339Nano)

	exec := func(query string, args ...any) {
		t.Helper()
		if _, err := db.ExecContext(ctx, query, args...); err != nil {
			t.Fatalf("seed v1 %q: %v", query, err)
		}
	}

	exec(`INSERT INTO platform_projects (id, name) VALUES ('proj-1', 'Checkout')`)
	exec(`INSERT INTO platform_agents (id, project_id, name) VALUES ('agent-1', 'proj-1', 'Deploy agent')`)
	exec(`INSERT INTO platform_candidates
		(id, agent_id, label, source_ref, artifact_digest, model, toolset_digest, config_digest)
		VALUES ('cand-1', 'agent-1', 'v1', 'abc123', '', '', '', '')`)
	exec(`INSERT INTO platform_evaluation_runs
		(id, candidate_id, environment, behavioral_profile, status, created_at, started_at, finished_at, failure_reason)
		VALUES (?, 'cand-1', 'staging', 'profile-1', 'running', ?, ?, NULL, '')`,
		runID, epoch, epoch)

	if records == 0 {
		return
	}

	count := uint64Text(records)
	zero := uint64Text(0)
	exec(`INSERT INTO platform_evaluation_aggregates (
		run_id, candidate_id, environment, behavioral_profile,
		record_count, first_observed_at, last_observed_at,
		decision_allow, decision_observe_only, decision_alert,
		decision_challenge, decision_require_approval, decision_block,
		risk_low, risk_medium, risk_high, risk_critical,
		approval_unspecified, approval_not_required, approval_required,
		approval_approved, approval_denied,
		policy_matched_rule, policy_matched_default,
		identity_confidence_count, identity_confidence_sum, identity_confidence_min, identity_confidence_max,
		anomaly_score_count, anomaly_score_sum, anomaly_score_min, anomaly_score_max,
		anomaly_confidence_count, anomaly_confidence_sum, anomaly_confidence_min, anomaly_confidence_max,
		trust_score_count, trust_score_sum, trust_score_min, trust_score_max,
		context_risk_count, context_risk_sum, context_risk_min, context_risk_max
	) VALUES (?, 'cand-1', 'staging', 'profile-1', ?, ?, ?,
		?, ?, ?, ?, ?, ?,
		?, ?, ?, ?,
		?, ?, ?, ?, ?,
		?, ?,
		?, 0.9, 0.9, 0.9,
		?, 0.4, 0.4, 0.4,
		?, 0.5, 0.5, 0.5,
		?, 0.8, 0.8, 0.8,
		?, 0.1, 0.1, 0.1)`,
		runID, count, epoch, epoch,
		count, zero, zero, zero, zero, zero, // decisions: all in allow
		count, zero, zero, zero, // risks: all low
		count, zero, zero, zero, zero, // approvals: all unspecified
		zero, count, // policy: all default
		count, count, count, count, count)

	exec(`INSERT INTO platform_behavior_snapshots
		(run_id, candidate_id, environment, behavioral_profile, observation_count, distinct_count, complete)
		VALUES (?, 'cand-1', 'staging', 'profile-1', ?, 1, 1)`, runID, count)

	exec(`INSERT INTO platform_behavior_entries
		(run_id, fingerprint_id, actor_type, operation_category, operation_name,
		 target_name, target_category, environment, observations)
		VALUES (?, 'fp-legacy', 'ai_agent', 'tool', 'legacy.op', 'build-host', 'external', 'staging', ?)`,
		runID, count)
}

// ---------------------------------------------------------------------
// Migration
// ---------------------------------------------------------------------

func TestFreshDatabaseIsSchemaV5(t *testing.T) {
	store, _ := testStore(t)
	version, err := store.storedSchemaVersion(t.Context())
	if err != nil {
		t.Fatalf("storedSchemaVersion() error = %v", err)
	}
	if version != SchemaVersion || SchemaVersion != 5 {
		t.Fatalf("version = %d, SchemaVersion = %d, want 5", version, SchemaVersion)
	}
	if err := store.requireTables(t.Context(), SchemaVersion, schemaTables); err != nil {
		t.Errorf("fresh database is missing tables: %v", err)
	}
}

// A real task 057 database migrates, and every row it held survives.
func TestSchemaV1MigratesToV2PreservingContent(t *testing.T) {
	path := filepath.Join(t.TempDir(), "v1.db")
	db := writeSchemaV1(t, path)
	seedV1Content(t, db, "run-legacy", 4)
	db.Close()

	store, err := OpenSQLiteStore(t.Context(), path)
	if err != nil {
		t.Fatalf("OpenSQLiteStore() on a v1 database error = %v", err)
	}
	defer store.Close()

	version, err := store.storedSchemaVersion(t.Context())
	if err != nil {
		t.Fatalf("storedSchemaVersion() error = %v", err)
	}
	if version != SchemaVersion {
		t.Fatalf("version = %d, want %d", version, SchemaVersion)
	}
	if err := store.requireTables(t.Context(), SchemaVersion, schemaTables); err != nil {
		t.Fatalf("migrated database is missing tables: %v", err)
	}

	t.Run("control state survives", func(t *testing.T) {
		project, err := store.Project(t.Context(), "proj-1")
		if err != nil || project.Name() != "Checkout" {
			t.Errorf("Project() = %v, %v", project.Name(), err)
		}
		candidate, err := store.Candidate(t.Context(), "cand-1")
		if err != nil || candidate.Metadata().SourceRef != "abc123" {
			t.Errorf("Candidate() metadata = %+v, %v", candidate.Metadata(), err)
		}
	})

	t.Run("evidence survives", func(t *testing.T) {
		aggregate, snapshot, err := store.EvaluationEvidence(t.Context(), "run-legacy")
		if err != nil {
			t.Fatalf("EvaluationEvidence() error = %v", err)
		}
		if aggregate.RecordCount() != 4 {
			t.Errorf("RecordCount() = %d, want 4", aggregate.RecordCount())
		}
		if snapshot.DistinctBehaviorCount() != 1 || !snapshot.Complete() {
			t.Errorf("snapshot = %d distinct, complete=%v",
				snapshot.DistinctBehaviorCount(), snapshot.Complete())
		}
	})

	// The migration edge: one ingest is one record, so evidence of N records
	// means the next sequence is N+1.
	t.Run("legacy evidence yields the right initial sequence", func(t *testing.T) {
		state, err := store.EvaluationIngestState(t.Context(), "run-legacy")
		if err != nil {
			t.Fatalf("EvaluationIngestState() error = %v", err)
		}
		if state.NextSequence() != 5 {
			t.Errorf("NextSequence() = %d, want 5", state.NextSequence())
		}
		// No digest is fabricated for a record this code never saw.
		if state.LastDigest() != "" {
			t.Errorf("LastDigest() = %q, want empty: a digest was invented", state.LastDigest())
		}
	})
}

// A run with no evidence starts at 1.
func TestMigratedRunWithoutEvidenceStartsAtOne(t *testing.T) {
	path := filepath.Join(t.TempDir(), "v1.db")
	db := writeSchemaV1(t, path)
	seedV1Content(t, db, "run-empty", 0)
	db.Close()

	store, err := OpenSQLiteStore(t.Context(), path)
	if err != nil {
		t.Fatalf("OpenSQLiteStore() error = %v", err)
	}
	defer store.Close()

	state, err := store.EvaluationIngestState(t.Context(), "run-empty")
	if err != nil {
		t.Fatalf("EvaluationIngestState() error = %v", err)
	}
	if state.NextSequence() != 1 {
		t.Errorf("NextSequence() = %d, want 1", state.NextSequence())
	}
}

// Without a recorded digest nothing can be proven identical, so a retry of the
// legacy last sequence conflicts rather than guessing.
func TestLegacyRetryCannotBeProvenIdentical(t *testing.T) {
	path := filepath.Join(t.TempDir(), "v1.db")
	db := writeSchemaV1(t, path)
	seedV1Content(t, db, "run-legacy", 4)
	db.Close()

	store, err := OpenSQLiteStore(t.Context(), path)
	if err != nil {
		t.Fatalf("OpenSQLiteStore() error = %v", err)
	}
	defer store.Close()

	plane, err := NewControlPlane(store, store, store)
	if err != nil {
		t.Fatalf("NewControlPlane() error = %v", err)
	}

	// Sequence 4 is the legacy last record; 5 is expected.
	_, err = plane.IngestDecisionRecord(t.Context(), IngestRequest{
		RunID:             "run-legacy",
		Sequence:          4,
		BehavioralProfile: "profile-1",
		Record:            internalRecord("evt-legacy", "fp-legacy", "legacy.op"),
	})
	if !errors.Is(err, ErrIngestSequence) {
		t.Fatalf("legacy retry error = %v, want ErrIngestSequence", err)
	}

	// And the expected sequence continues the count rather than restarting it.
	result, err := plane.IngestDecisionRecord(t.Context(), IngestRequest{
		RunID:             "run-legacy",
		Sequence:          5,
		BehavioralProfile: "profile-1",
		Record:            internalRecord("evt-next", "fp-legacy", "legacy.op"),
	})
	if err != nil {
		t.Fatalf("ingest at the expected sequence error = %v", err)
	}
	if result.RecordCount != 5 {
		t.Errorf("RecordCount = %d, want 5: legacy evidence was not continued", result.RecordCount)
	}
}

// A v1 database missing a table is damage, and migrating on top of damage
// would bury it under a version number claiming everything is fine.
func TestPartialV1IsNotMigrated(t *testing.T) {
	path := filepath.Join(t.TempDir(), "v1.db")
	db := writeSchemaV1(t, path)
	if _, err := db.Exec(`DROP TABLE platform_behavior_entries`); err != nil {
		t.Fatalf("drop: %v", err)
	}
	db.Close()

	store, err := OpenSQLiteStore(t.Context(), path)
	if !errors.Is(err, ErrStoreSchemaVersion) {
		if store != nil {
			store.Close()
		}
		t.Fatalf("OpenSQLiteStore() error = %v, want ErrStoreSchemaVersion", err)
	}

	// Still a v1 database: nothing was stamped.
	raw, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatalf("sql.Open() error = %v", err)
	}
	defer raw.Close()
	var version int
	if err := raw.QueryRow(`SELECT version FROM platform_schema_version WHERE id = 1`).Scan(&version); err != nil {
		t.Fatalf("read version: %v", err)
	}
	if version != 1 {
		t.Errorf("version = %d, want 1: a partial database was stamped", version)
	}
}

func TestUnknownVersionIsNotMigrated(t *testing.T) {
	path := filepath.Join(t.TempDir(), "v1.db")
	db := writeSchemaV1(t, path)
	if _, err := db.Exec(`UPDATE platform_schema_version SET version = 99`); err != nil {
		t.Fatalf("update: %v", err)
	}
	db.Close()

	store, err := OpenSQLiteStore(t.Context(), path)
	if !errors.Is(err, ErrStoreSchemaVersion) {
		if store != nil {
			store.Close()
		}
		t.Fatalf("OpenSQLiteStore() error = %v, want ErrStoreSchemaVersion", err)
	}
}

// A failed migration leaves a readable v1 rather than a half-stamped hybrid.
func TestFailedMigrationRollsBackToV1(t *testing.T) {
	path := filepath.Join(t.TempDir(), "v1.db")
	db := writeSchemaV1(t, path)
	seedV1Content(t, db, "run-legacy", 2)

	// Occupy the name the migration needs, so creating it fails.
	if _, err := db.Exec(`CREATE TABLE platform_evaluation_ingest_state (blocker TEXT)`); err != nil {
		t.Fatalf("create blocker: %v", err)
	}
	db.Close()

	store, err := OpenSQLiteStore(t.Context(), path)
	if err == nil {
		store.Close()
		t.Fatal("migration succeeded despite a conflicting table")
	}

	raw, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatalf("sql.Open() error = %v", err)
	}
	defer raw.Close()
	var version int
	if err := raw.QueryRow(`SELECT version FROM platform_schema_version WHERE id = 1`).Scan(&version); err != nil {
		t.Fatalf("read version: %v", err)
	}
	if version != 1 {
		t.Errorf("version = %d, want 1: a failed migration stamped the database", version)
	}
	var projects int
	if err := raw.QueryRow(`SELECT COUNT(*) FROM platform_projects`).Scan(&projects); err != nil {
		t.Fatalf("count: %v", err)
	}
	if projects != 1 {
		t.Errorf("projects = %d, want 1: a failed migration lost content", projects)
	}
}

// ---------------------------------------------------------------------
// Cursor and evidence consistency
// ---------------------------------------------------------------------

// A cursor that disagrees with the evidence it describes means one was
// written without the other, and there is no principled way to pick a side.
func TestCursorEvidenceDivergenceIsCorrupt(t *testing.T) {
	store, _ := testStore(t)
	ctx := t.Context()
	run := seedRunningRun(t, store)

	plane, err := NewControlPlane(store, store, store)
	if err != nil {
		t.Fatalf("NewControlPlane() error = %v", err)
	}
	if _, err := plane.IngestDecisionRecord(ctx, IngestRequest{
		RunID: run.ID(), Sequence: 1, BehavioralProfile: run.BehavioralProfile(),
		Record: internalRecord("evt-0", "fp-0", "op-0"),
	}); err != nil {
		t.Fatalf("ingest error = %v", err)
	}

	// Advance the cursor without advancing the evidence.
	exec(t, store.db, `UPDATE `+tableIngestState+` SET next_sequence = ? WHERE run_id = ?`,
		uint64Text(99), string(run.ID()))

	if _, err := store.EvaluationIngestState(ctx, run.ID()); !errors.Is(err, ErrStoreCorrupt) {
		t.Fatalf("EvaluationIngestState() error = %v, want ErrStoreCorrupt", err)
	}
}

// A cursor for a run with no evidence at all is equally impossible.
func TestCursorWithoutEvidenceIsCorrupt(t *testing.T) {
	store, _ := testStore(t)
	run := seedRunningRun(t, store)

	exec(t, store.db, `INSERT INTO `+tableIngestState+` (run_id, next_sequence, last_digest)
		VALUES (?, ?, '')`, string(run.ID()), uint64Text(3))

	if _, err := store.EvaluationIngestState(t.Context(), run.ID()); !errors.Is(err, ErrStoreCorrupt) {
		t.Fatalf("error = %v, want ErrStoreCorrupt", err)
	}
}

func TestStoredCursorRejectsNonCanonicalAndZero(t *testing.T) {
	store, _ := testStore(t)
	ctx := t.Context()
	run := seedRunningRun(t, store)

	plane, _ := NewControlPlane(store, store, store)
	if _, err := plane.IngestDecisionRecord(ctx, IngestRequest{
		RunID: run.ID(), Sequence: 1, BehavioralProfile: run.BehavioralProfile(),
		Record: internalRecord("evt-0", "fp-0", "op-0"),
	}); err != nil {
		t.Fatalf("ingest error = %v", err)
	}

	for _, bad := range []string{"007", "-1", "", "0"} {
		t.Run(fmt.Sprintf("%q", bad), func(t *testing.T) {
			exec(t, store.db, `UPDATE `+tableIngestState+` SET next_sequence = ? WHERE run_id = ?`,
				bad, string(run.ID()))
			if _, err := store.EvaluationIngestState(ctx, run.ID()); !errors.Is(err, ErrStoreCorrupt) {
				t.Errorf("error = %v, want ErrStoreCorrupt", err)
			}
		})
	}
}

func TestStoredDigestMustBeSHA256(t *testing.T) {
	store, _ := testStore(t)
	ctx := t.Context()
	run := seedRunningRun(t, store)

	plane, _ := NewControlPlane(store, store, store)
	if _, err := plane.IngestDecisionRecord(ctx, IngestRequest{
		RunID: run.ID(), Sequence: 1, BehavioralProfile: run.BehavioralProfile(),
		Record: internalRecord("evt-0", "fp-0", "op-0"),
	}); err != nil {
		t.Fatalf("ingest error = %v", err)
	}

	for _, bad := range []string{"tooshort", "zz" + string(make([]byte, 0)) + "not-hex-at-all-but-64-characters-long-padding-padding-padding!!"} {
		exec(t, store.db, `UPDATE `+tableIngestState+` SET last_digest = ? WHERE run_id = ?`,
			bad, string(run.ID()))
		if _, err := store.EvaluationIngestState(ctx, run.ID()); !errors.Is(err, ErrStoreCorrupt) {
			t.Errorf("digest %q error = %v, want ErrStoreCorrupt", bad, err)
		}
	}
}

// ---------------------------------------------------------------------
// Atomicity
// ---------------------------------------------------------------------

// Evidence and cursor advance together or not at all. Split, the two failure
// modes are silent: evidence without the cursor makes the next retry
// double-count, and the cursor without evidence loses a record the protocol
// believes arrived.
func TestIngestCommitIsAtomic(t *testing.T) {
	store, _ := testStore(t)
	ctx := t.Context()
	run := seedRunningRun(t, store)

	plane, err := NewControlPlane(store, store, store)
	if err != nil {
		t.Fatalf("NewControlPlane() error = %v", err)
	}

	// Two records applied normally.
	for i := range 2 {
		if _, err := plane.IngestDecisionRecord(ctx, IngestRequest{
			RunID: run.ID(), Sequence: uint64(i + 1), BehavioralProfile: run.BehavioralProfile(),
			Record: internalRecord(fmt.Sprintf("evt-%d", i), fmt.Sprintf("fp-%d", i), fmt.Sprintf("op-%d", i)),
		}); err != nil {
			t.Fatalf("ingest %d error = %v", i+1, err)
		}
	}

	before, _, err := store.EvaluationEvidence(ctx, run.ID())
	if err != nil {
		t.Fatalf("EvaluationEvidence() error = %v", err)
	}
	beforeState, err := store.EvaluationIngestState(ctx, run.ID())
	if err != nil {
		t.Fatalf("EvaluationIngestState() error = %v", err)
	}

	// Fail the cursor write specifically, after the evidence writes in the
	// same transaction have already been issued.
	exec(t, store.db, `CREATE TRIGGER fail_cursor BEFORE UPDATE ON `+tableIngestState+`
		BEGIN SELECT RAISE(ABORT, 'injected failure'); END`)

	_, err = plane.IngestDecisionRecord(ctx, IngestRequest{
		RunID: run.ID(), Sequence: 3, BehavioralProfile: run.BehavioralProfile(),
		Record: internalRecord("evt-2", "fp-2", "op-2"),
	})
	if err == nil {
		t.Fatal("ingest succeeded despite the injected cursor failure")
	}

	exec(t, store.db, `DROP TRIGGER fail_cursor`)

	after, _, err := store.EvaluationEvidence(ctx, run.ID())
	if err != nil {
		t.Fatalf("EvaluationEvidence() error = %v", err)
	}
	afterState, err := store.EvaluationIngestState(ctx, run.ID())
	if err != nil {
		t.Fatalf("EvaluationIngestState() error = %v", err)
	}

	if after.RecordCount() != before.RecordCount() {
		t.Errorf("RecordCount() = %d, want %d: evidence advanced without the cursor",
			after.RecordCount(), before.RecordCount())
	}
	if afterState.NextSequence() != beforeState.NextSequence() {
		t.Errorf("NextSequence() = %d, want %d", afterState.NextSequence(), beforeState.NextSequence())
	}

	// And the protocol still works afterwards: sequence 3 is still expected.
	if _, err := plane.IngestDecisionRecord(ctx, IngestRequest{
		RunID: run.ID(), Sequence: 3, BehavioralProfile: run.BehavioralProfile(),
		Record: internalRecord("evt-2", "fp-2", "op-2"),
	}); err != nil {
		t.Fatalf("ingest after rollback error = %v", err)
	}
}

// ---------------------------------------------------------------------
// Sequence arithmetic
// ---------------------------------------------------------------------

func TestSequenceDoesNotWrap(t *testing.T) {
	if _, err := nextSequenceAfter(math.MaxUint64); !errors.Is(err, ErrIngestSequence) {
		t.Errorf("nextSequenceAfter(MaxUint64) error = %v, want ErrIngestSequence", err)
	}
	if next, err := nextSequenceAfter(math.MaxUint64 - 1); err != nil || next != math.MaxUint64 {
		t.Errorf("nextSequenceAfter(MaxUint64-1) = %d, %v", next, err)
	}
	// A run already holding MaxUint64 records has no valid next sequence.
	if _, err := initialSequenceFor(math.MaxUint64); !errors.Is(err, ErrIngestSequence) {
		t.Errorf("initialSequenceFor(MaxUint64) error = %v, want ErrIngestSequence", err)
	}
}

func TestParseSequenceRejectsNonCanonical(t *testing.T) {
	for _, bad := range []string{"", "0", "01", "+1", "-1", "1.0", " 1", "1 ", "abc",
		"18446744073709551616"} {
		if _, err := ParseSequence(bad); !errors.Is(err, ErrIngestSequence) {
			t.Errorf("ParseSequence(%q) error = %v, want ErrIngestSequence", bad, err)
		}
	}
	for _, good := range []string{"1", "2", "18446744073709551615"} {
		if _, err := ParseSequence(good); err != nil {
			t.Errorf("ParseSequence(%q) error = %v", good, err)
		}
	}
}

// The digest is taken over the decoded record, so formatting differences in
// the request do not make a genuine retry look like a different record.
func TestRecordDigestIsStableAcrossEncoding(t *testing.T) {
	record := internalRecord("evt-0", "fp-0", "op-0")
	first, err := RecordDigest(record)
	if err != nil {
		t.Fatalf("RecordDigest() error = %v", err)
	}
	// A copy through a different path produces the same digest.
	second, err := RecordDigest(record)
	if err != nil {
		t.Fatalf("RecordDigest() error = %v", err)
	}
	if first != second {
		t.Errorf("digest is not stable: %q vs %q", first, second)
	}

	different := internalRecord("evt-1", "fp-0", "op-0")
	other, err := RecordDigest(different)
	if err != nil {
		t.Fatalf("RecordDigest() error = %v", err)
	}
	if other == first {
		t.Error("two different records share a digest")
	}
}

// ---------------------------------------------------------------------
// Collector restoration
// ---------------------------------------------------------------------

// The restored collector must not alias the snapshot it came from.
func TestRestoredCollectorDoesNotAliasSnapshot(t *testing.T) {
	store, _ := testStore(t)
	ctx := t.Context()
	run := seedRunningRun(t, store)

	plane, _ := NewControlPlane(store, store, store)
	if _, err := plane.IngestDecisionRecord(ctx, IngestRequest{
		RunID: run.ID(), Sequence: 1, BehavioralProfile: run.BehavioralProfile(),
		Record: internalRecord("evt-0", "fp-0", "op-0"),
	}); err != nil {
		t.Fatalf("ingest error = %v", err)
	}

	_, snapshot, err := store.EvaluationEvidence(ctx, run.ID())
	if err != nil {
		t.Fatalf("EvaluationEvidence() error = %v", err)
	}

	collector, err := behaviorCollectorFromSnapshot(snapshot)
	if err != nil {
		t.Fatalf("behaviorCollectorFromSnapshot() error = %v", err)
	}
	if err := collector.Observe(internalRecord("evt-1", "fp-1", "op-1")); err != nil {
		t.Fatalf("Observe() error = %v", err)
	}

	// The original snapshot is untouched.
	if snapshot.DistinctBehaviorCount() != 1 {
		t.Errorf("the snapshot changed to %d entries; the collector aliased its storage",
			snapshot.DistinctBehaviorCount())
	}
	if collector.Snapshot().DistinctBehaviorCount() != 2 {
		t.Errorf("collector = %d entries, want 2", collector.Snapshot().DistinctBehaviorCount())
	}
}

func TestUnboundSnapshotCannotRestoreACollector(t *testing.T) {
	if _, err := behaviorCollectorFromSnapshot(BehaviorSnapshot{}); !errors.Is(err, ErrUnboundCollector) {
		t.Errorf("error = %v, want ErrUnboundCollector", err)
	}
}

// seedRunningRun creates the hierarchy and leaves the run running.
func seedRunningRun(t *testing.T, store *SQLiteStore) EvaluationRun {
	t.Helper()
	run := seedRun(t, store)
	started, err := run.Start(run.CreatedAt().Add(time.Minute))
	if err != nil {
		t.Fatalf("Start() error = %v", err)
	}
	if err := store.UpdateEvaluationRun(t.Context(), run, started); err != nil {
		t.Fatalf("UpdateEvaluationRun() error = %v", err)
	}
	return started
}

// ---------------------------------------------------------------------
// Terminal transition versus ingest
// ---------------------------------------------------------------------

// A completed evaluation has final evidence. The service prechecks Running
// before computing evidence, so a completion committing in between would let
// an ingest land afterwards — and the durable transaction is what forbids it.
//
// The interleaving is pinned with a trigger rather than timing: the run is
// completed between the service's preflight and the durable commit, by
// completing it *before* the commit is attempted with a stale view.
func TestIngestCannotCommitAfterRunBecomesTerminal(t *testing.T) {
	store, _ := testStore(t)
	ctx := t.Context()
	run := seedRunningRun(t, store)

	plane, err := NewControlPlane(store, store, store)
	if err != nil {
		t.Fatalf("NewControlPlane() error = %v", err)
	}

	// One record, so there is evidence and a cursor to compare against.
	if _, err := plane.IngestDecisionRecord(ctx, IngestRequest{
		RunID: run.ID(), Sequence: 1, BehavioralProfile: run.BehavioralProfile(),
		Record: internalRecord("evt-0", "fp-0", "op-0"),
	}); err != nil {
		t.Fatalf("first ingest error = %v", err)
	}

	beforeAggregate, _, err := store.EvaluationEvidence(ctx, run.ID())
	if err != nil {
		t.Fatalf("EvaluationEvidence() error = %v", err)
	}
	beforeState, err := store.EvaluationIngestState(ctx, run.ID())
	if err != nil {
		t.Fatalf("EvaluationIngestState() error = %v", err)
	}

	// The run completes.
	if _, err := plane.CompleteEvaluationRun(ctx, run.ID(), run.CreatedAt().Add(time.Hour)); err != nil {
		t.Fatalf("CompleteEvaluationRun() error = %v", err)
	}

	// A commit built from the pre-completion view — exactly what an ingest
	// that passed preflight before the completion would attempt.
	aggregate, collector := staleEvidenceFor(t, store, run)
	staleAggregate, err := aggregate.AddRecord(internalRecord("evt-1", "fp-1", "op-1"))
	if err != nil {
		t.Fatalf("AddRecord() error = %v", err)
	}
	if err := collector.Observe(internalRecord("evt-1", "fp-1", "op-1")); err != nil {
		t.Fatalf("Observe() error = %v", err)
	}

	_, err = store.CommitEvaluationIngest(ctx, EvaluationIngestCommit{
		PreviousNextSequence: beforeState.NextSequence(),
		Sequence:             beforeState.NextSequence(),
		RecordDigest:         mustDigest(t, internalRecord("evt-1", "fp-1", "op-1")),
		Aggregate:            staleAggregate,
		Snapshot:             collector.Snapshot(),
	})
	if !errors.Is(err, ErrEvaluationState) {
		t.Fatalf("commit after completion error = %v, want ErrEvaluationState", err)
	}

	// Nothing moved.
	afterAggregate, _, err := store.EvaluationEvidence(ctx, run.ID())
	if err != nil {
		t.Fatalf("EvaluationEvidence() error = %v", err)
	}
	if afterAggregate.RecordCount() != beforeAggregate.RecordCount() {
		t.Errorf("RecordCount() = %d, want %d: evidence grew after completion",
			afterAggregate.RecordCount(), beforeAggregate.RecordCount())
	}
	afterState, err := store.EvaluationIngestState(ctx, run.ID())
	if err != nil {
		t.Fatalf("EvaluationIngestState() error = %v", err)
	}
	if afterState.NextSequence() != beforeState.NextSequence() {
		t.Errorf("NextSequence() = %d, want %d", afterState.NextSequence(), beforeState.NextSequence())
	}

	stored, err := store.EvaluationRun(ctx, run.ID())
	if err != nil {
		t.Fatalf("EvaluationRun() error = %v", err)
	}
	if stored.Status() != RunCompleted {
		t.Errorf("Status() = %q, want completed", stored.Status())
	}
}

// The inverse ordering is legitimate: an ingest that commits before the
// completion belongs to the run's final evidence.
func TestIngestThenCompleteBothSucceed(t *testing.T) {
	store, _ := testStore(t)
	ctx := t.Context()
	run := seedRunningRun(t, store)

	plane, err := NewControlPlane(store, store, store)
	if err != nil {
		t.Fatalf("NewControlPlane() error = %v", err)
	}
	if _, err := plane.IngestDecisionRecord(ctx, IngestRequest{
		RunID: run.ID(), Sequence: 1, BehavioralProfile: run.BehavioralProfile(),
		Record: internalRecord("evt-0", "fp-0", "op-0"),
	}); err != nil {
		t.Fatalf("ingest error = %v", err)
	}
	if _, err := plane.CompleteEvaluationRun(ctx, run.ID(), run.CreatedAt().Add(time.Hour)); err != nil {
		t.Fatalf("CompleteEvaluationRun() error = %v", err)
	}

	aggregate, _, err := store.EvaluationEvidence(ctx, run.ID())
	if err != nil {
		t.Fatalf("EvaluationEvidence() error = %v", err)
	}
	if aggregate.RecordCount() != 1 {
		t.Errorf("RecordCount() = %d, want 1: the record was lost", aggregate.RecordCount())
	}
}

// staleEvidenceFor rebuilds a run's current evidence, as an in-flight ingest
// would hold it.
func staleEvidenceFor(t *testing.T, store *SQLiteStore, run EvaluationRun) (EvaluationAggregate, *BehaviorCollector) {
	t.Helper()
	aggregate, snapshot, err := store.EvaluationEvidence(t.Context(), run.ID())
	if err != nil {
		t.Fatalf("EvaluationEvidence() error = %v", err)
	}
	collector, err := behaviorCollectorFromSnapshot(snapshot)
	if err != nil {
		t.Fatalf("behaviorCollectorFromSnapshot() error = %v", err)
	}
	return aggregate, collector
}

func mustDigest(t *testing.T, record trustvian.DecisionRecord) string {
	t.Helper()
	digest, err := RecordDigest(record)
	if err != nil {
		t.Fatalf("RecordDigest() error = %v", err)
	}
	return digest
}

// ---------------------------------------------------------------------
// Persisted digest invariant
// ---------------------------------------------------------------------

// A cursor row was written by the commit path, which always records a digest.
// An empty one cannot have been produced legitimately.
func TestPersistedCursorRequiresCanonicalDigest(t *testing.T) {
	tests := []struct {
		name   string
		digest string
	}{
		{"empty", ""},
		{"too short", "abc123"},
		{"not hex", "zzzz5c3f2b1a0908070605040302010009080706050403020100090807060504"},
		{"uppercase", "ABCDEF1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF1234567890"},
		{"too long", "ab" + "cdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890ab"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			store, _ := testStore(t)
			ctx := t.Context()
			run := seedRunningRun(t, store)

			plane, _ := NewControlPlane(store, store, store)
			if _, err := plane.IngestDecisionRecord(ctx, IngestRequest{
				RunID: run.ID(), Sequence: 1, BehavioralProfile: run.BehavioralProfile(),
				Record: internalRecord("evt-0", "fp-0", "op-0"),
			}); err != nil {
				t.Fatalf("ingest error = %v", err)
			}

			exec(t, store.db, `UPDATE `+tableIngestState+` SET last_digest = ? WHERE run_id = ?`,
				tt.digest, string(run.ID()))

			if _, err := store.EvaluationIngestState(ctx, run.ID()); !errors.Is(err, ErrStoreCorrupt) {
				t.Fatalf("EvaluationIngestState() error = %v, want ErrStoreCorrupt", err)
			}
		})
	}
}

// The legitimate empty digest: derived legacy state with no cursor row. The
// distinction is row presence, not the value.
func TestDerivedLegacyStateMayHaveNoDigest(t *testing.T) {
	path := filepath.Join(t.TempDir(), "v1.db")
	db := writeSchemaV1(t, path)
	seedV1Content(t, db, "run-legacy", 3)
	db.Close()

	store, err := OpenSQLiteStore(t.Context(), path)
	if err != nil {
		t.Fatalf("OpenSQLiteStore() error = %v", err)
	}
	defer store.Close()

	state, err := store.EvaluationIngestState(t.Context(), "run-legacy")
	if err != nil {
		t.Fatalf("EvaluationIngestState() error = %v", err)
	}
	if state.LastDigest() != "" {
		t.Errorf("LastDigest() = %q, want empty", state.LastDigest())
	}
	if state.NextSequence() != 4 {
		t.Errorf("NextSequence() = %d, want 4", state.NextSequence())
	}
}

// ---------------------------------------------------------------------
// Concurrent migration
// ---------------------------------------------------------------------

// Several openers racing one v1 database must converge on a single valid v2,
// with every v1 row intact. A losing attempt can fail at any statement, not
// only the commit, so recovery inspects the durable schema rather than the
// error text.
func TestConcurrentMigrationConvergesOnValidV2(t *testing.T) {
	path := filepath.Join(t.TempDir(), "v1.db")
	db := writeSchemaV1(t, path)
	seedV1Content(t, db, "run-legacy", 4)
	db.Close()

	const openers = 8
	var start sync.WaitGroup
	start.Add(1)
	var done sync.WaitGroup
	stores := make([]*SQLiteStore, openers)
	errs := make([]error, openers)

	for i := range openers {
		done.Add(1)
		go func() {
			defer done.Done()
			start.Wait() // a barrier, not a sleep
			stores[i], errs[i] = OpenSQLiteStore(context.Background(), path)
		}()
	}
	start.Done()
	done.Wait()

	for i, err := range errs {
		if err != nil {
			t.Errorf("opener %d failed: %v", i, err)
		}
	}
	for _, store := range stores {
		if store != nil {
			store.Close()
		}
	}

	// One valid v2, and the v1 content survived exactly.
	reopened, err := OpenSQLiteStore(t.Context(), path)
	if err != nil {
		t.Fatalf("reopen after the race error = %v", err)
	}
	defer reopened.Close()

	version, err := reopened.storedSchemaVersion(t.Context())
	if err != nil || version != SchemaVersion {
		t.Fatalf("version = %d, %v; want %d", version, err, SchemaVersion)
	}
	if err := reopened.requireTables(t.Context(), SchemaVersion, schemaTables); err != nil {
		t.Fatalf("migrated schema is incomplete: %v", err)
	}

	project, err := reopened.Project(t.Context(), "proj-1")
	if err != nil || project.Name() != "Checkout" {
		t.Errorf("Project() = %q, %v", project.Name(), err)
	}
	aggregate, _, err := reopened.EvaluationEvidence(t.Context(), "run-legacy")
	if err != nil {
		t.Fatalf("EvaluationEvidence() error = %v", err)
	}
	if aggregate.RecordCount() != 4 {
		t.Errorf("RecordCount() = %d, want 4", aggregate.RecordCount())
	}
	state, err := reopened.EvaluationIngestState(t.Context(), "run-legacy")
	if err != nil {
		t.Fatalf("EvaluationIngestState() error = %v", err)
	}
	if state.NextSequence() != 5 {
		t.Errorf("NextSequence() = %d, want 5", state.NextSequence())
	}
	if state.LastDigest() != "" {
		t.Errorf("LastDigest() = %q, want empty: a digest was invented", state.LastDigest())
	}
}

// ---------------------------------------------------------------------
// The empty-evidence fallback must not heal corruption
// ---------------------------------------------------------------------

// A completed run whose evidence rows were deleted while its cursor survives
// is impossible durable state, not an empty evaluation.
//
// This is the test the zero-record fallback exists to not break: absence of
// evidence is only emptiness when nothing was ever written, and the cursor
// row is the proof that something was.
func TestZeroEvidenceFallbackDoesNotMaskMissingEvidence(t *testing.T) {
	store, _ := testStore(t)
	ctx := t.Context()
	run := seedRunningRun(t, store)

	plane, err := NewControlPlane(store, store, store)
	if err != nil {
		t.Fatalf("NewControlPlane() error = %v", err)
	}
	if _, err := plane.IngestDecisionRecord(ctx, IngestRequest{
		RunID: run.ID(), Sequence: 1, BehavioralProfile: run.BehavioralProfile(),
		Record: internalRecord("evt-0", "fp-0", "op-0"),
	}); err != nil {
		t.Fatalf("ingest error = %v", err)
	}
	completed, err := plane.CompleteEvaluationRun(ctx, run.ID(), run.CreatedAt().Add(time.Hour))
	if err != nil {
		t.Fatalf("CompleteEvaluationRun() error = %v", err)
	}
	_ = completed

	// A second completed run to compare against.
	reference := seedSecondCompletedRun(t, store, plane)

	// Delete the evidence, keep the cursor.
	exec(t, store.db, `PRAGMA foreign_keys = OFF`)
	exec(t, store.db, `DELETE FROM `+tableEntries+` WHERE run_id = ?`, string(run.ID()))
	exec(t, store.db, `DELETE FROM `+tableSnapshots+` WHERE run_id = ?`, string(run.ID()))
	exec(t, store.db, `DELETE FROM `+tableAggregates+` WHERE run_id = ?`, string(run.ID()))

	_, err = plane.CompareEvaluations(ctx, reference, run.ID(), EvaluationGateLimits{
		MaxAddedBehaviors:           math.MaxUint64,
		MaxBlockDecisions:           math.MaxUint64,
		MaxCriticalRiskObservations: math.MaxUint64,
	})
	if !errors.Is(err, ErrStoreCorrupt) {
		t.Fatalf("CompareEvaluations() error = %v, want ErrStoreCorrupt; "+
			"a cursor without evidence was treated as an empty evaluation", err)
	}
}

// Partial evidence stays corruption through the comparison path too.
func TestZeroEvidenceFallbackDoesNotMaskPartialEvidence(t *testing.T) {
	store, _ := testStore(t)
	ctx := t.Context()
	run := seedRunningRun(t, store)

	plane, err := NewControlPlane(store, store, store)
	if err != nil {
		t.Fatalf("NewControlPlane() error = %v", err)
	}
	if _, err := plane.IngestDecisionRecord(ctx, IngestRequest{
		RunID: run.ID(), Sequence: 1, BehavioralProfile: run.BehavioralProfile(),
		Record: internalRecord("evt-0", "fp-0", "op-0"),
	}); err != nil {
		t.Fatalf("ingest error = %v", err)
	}
	if _, err := plane.CompleteEvaluationRun(ctx, run.ID(), run.CreatedAt().Add(time.Hour)); err != nil {
		t.Fatalf("CompleteEvaluationRun() error = %v", err)
	}
	reference := seedSecondCompletedRun(t, store, plane)

	// Aggregate survives, snapshot does not.
	exec(t, store.db, `PRAGMA foreign_keys = OFF`)
	exec(t, store.db, `DELETE FROM `+tableEntries+` WHERE run_id = ?`, string(run.ID()))
	exec(t, store.db, `DELETE FROM `+tableSnapshots+` WHERE run_id = ?`, string(run.ID()))

	_, err = plane.CompareEvaluations(ctx, reference, run.ID(), EvaluationGateLimits{
		MaxAddedBehaviors:           math.MaxUint64,
		MaxBlockDecisions:           math.MaxUint64,
		MaxCriticalRiskObservations: math.MaxUint64,
	})
	if !errors.Is(err, ErrStoreCorrupt) {
		t.Fatalf("CompareEvaluations() error = %v, want ErrStoreCorrupt", err)
	}
}

// seedSecondCompletedRun creates another completed run with one record.
func seedSecondCompletedRun(t *testing.T, store *SQLiteStore, plane *ControlPlane) EvaluationRunID {
	t.Helper()
	ctx := t.Context()
	const id EvaluationRunID = "run-reference"

	candidate, err := NewCandidate("cand-ref", "agent-1", CandidateMetadata{})
	if err != nil {
		t.Fatalf("NewCandidate() error = %v", err)
	}
	if err := store.CreateCandidate(ctx, candidate); err != nil {
		t.Fatalf("CreateCandidate() error = %v", err)
	}
	epoch := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	run, err := NewEvaluationRun(id, "cand-ref", "staging", "profile-1", epoch)
	if err != nil {
		t.Fatalf("NewEvaluationRun() error = %v", err)
	}
	if err := store.CreateEvaluationRun(ctx, run); err != nil {
		t.Fatalf("CreateEvaluationRun() error = %v", err)
	}
	if _, err := plane.StartEvaluationRun(ctx, id, epoch.Add(time.Minute)); err != nil {
		t.Fatalf("StartEvaluationRun() error = %v", err)
	}
	if _, err := plane.IngestDecisionRecord(ctx, IngestRequest{
		RunID: id, Sequence: 1, BehavioralProfile: "profile-1",
		Record: internalRecord("ref-evt-0", "ref-fp-0", "ref-op-0"),
	}); err != nil {
		t.Fatalf("ingest error = %v", err)
	}
	if _, err := plane.CompleteEvaluationRun(ctx, id, epoch.Add(time.Hour)); err != nil {
		t.Fatalf("CompleteEvaluationRun() error = %v", err)
	}
	return id
}
