package main

// Composing the OTLP receiver for `trustvian dev`.
//
// dev does not own a receiver. It starts trustvian-collector, which already
// carries the OTLP protocol stack — gRPC and HTTP, compression, partial success,
// backpressure — and the Trustvian processor that scores what arrives. Owning
// that stack here would mean maintaining it here, and task 073's processor is
// the right answer for fan-out deployments and is not deprecated by this.
//
// The configuration is generated as text. The root CLI may not import a YAML
// library — .claude/rules/go.md confines go.yaml.in/yaml/v3 to the config
// package — and a text/template is sufficient for a fixed-shape document with a
// handful of substituted scalars. That makes this a contract expressed in text
// rather than in types, which is the same shape ADR 0035 §9 chose for the
// discovery file: both sides implement one format, neither imports the other.
// docs/compatibility.md already classifies the processor's configuration keys
// OPERATIONALLY STABLE, so the surface being written here is one with a promise
// attached.

import (
	"errors"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"text/template"
	"time"
)

const (
	// collectorConfigFile is written into dev's state directory, never into the
	// workload's repository.
	collectorConfigFile = "collector.yaml"

	// collectorLogFile keeps the Collector's own output off the workload's
	// streams, for the same reason the runtime's log does.
	collectorLogFile = "collector.log"

	// collectorPollInterval is how often readiness is re-checked.
	collectorPollInterval = 25 * time.Millisecond

	// collectorProbeTimeout bounds one readiness request.
	collectorProbeTimeout = 2 * time.Second

	// collectorPortAttempts bounds retries when a chosen port is taken.
	//
	// Port selection is advisory: dev binds :0 to learn a free port and closes
	// it before the Collector binds, so another process can take it in between.
	// Rare, and retried rather than reported, because a collision is not a
	// failure the developer can act on.
	collectorPortAttempts = 3
)

// Waiting bounds, as variables so tests can shorten them.
var (
	// collectorReadyTimeout bounds waiting for the Collector to serve.
	//
	// Generous: it builds a pipeline and opens a store. A developer waiting
	// beats a timeout that fires on a slow machine.
	collectorReadyTimeout = 45 * time.Second

	// collectorStopGrace is how long a SIGTERM'd Collector has to flush and
	// exit before it is killed. Longer than the runtime's, because it may be
	// draining a span batch, and a dropped batch is lost evidence.
	collectorStopGrace = 10 * time.Second
)

// collectorTemplate is the generated Collector configuration.
//
// Traces only: metrics and logs pipelines would receive nothing dev asked for
// and would widen what this process accepts for no benefit.
//
// Both OTLP protocols are enabled, and that is not hedging. dev steers any SDK
// that reads the environment to http/protobuf, but a workload that builds its
// exporter in code chooses its own transport and never consults
// OTEL_EXPORTER_OTLP_PROTOCOL — this repository's own processor/cmd/demo-producer
// uses otlptracegrpc exactly that way. An HTTP-only receiver would silently
// observe nothing from it, which is the failure mode this whole command exists to
// remove. The roadmap's principle is "if it emits OpenTelemetry, Trustvian can
// observe it", and one extra loopback port is a small price for meaning it.
//
// The debug exporter is the terminus because a pipeline needs one and dev has
// nowhere else to send spans. Its verbosity is `basic`, so it does not print
// span attributes — this process must not become a way to read prompt content
// out of a log (tasks 075 and 076 own that boundary, and neither has moved).
//
// There is deliberately no `service.telemetry:` block. trustvian-collector is
// assembled with a minimal telemetry factory whose configuration type is
// struct{}, so it accepts no keys there at all and rejects the whole document if
// any appear — which is what the repository's own processor/config.yaml
// demonstrates by omitting it too. The Collector's own logs land in
// collector.log, which is where a diagnostic reads them from.
var collectorTemplate = template.Must(template.New("collector").Parse(
	`# Generated by 'trustvian dev'. Do not edit: it is rewritten on every run,
# and it lives in dev's state directory rather than in your repository.
receivers:
  otlp:
    protocols:
      http:
        endpoint: 127.0.0.1:{{.OTLPHTTPPort}}
      grpc:
        endpoint: 127.0.0.1:{{.OTLPGRPCPort}}

processors:
  trustvian:
    health:
      endpoint: 127.0.0.1:{{.HealthPort}}
      readiness_timeout: 2s

exporters:
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [trustvian]
      exporters: [debug]
`))

// collectorConfigData is what the template substitutes.
//
// Integers, not strings. That is deliberate: every value written into the
// generated document is a port this process chose, so there is no string from
// an untrusted source to quote or escape. When slice 3 adds a run id and a
// behavioral profile, they arrive as strings and will need validating before
// they reach this struct — see validateCollectorScalar.
type collectorConfigData struct {
	OTLPHTTPPort int
	OTLPGRPCPort int
	HealthPort   int
}

// collector is a supervised trustvian-collector process.
type collector struct {
	cmd *exec.Cmd
	// httpPort is what the workload's environment points at; grpcPort is there
	// for a workload that chose its transport in code.
	httpPort int
	grpcPort int
	logPath  string

	waited   chan error
	stopOnce sync.Once
}

// startCollector writes a configuration, launches the Collector, and waits
// until it can actually receive.
func startCollector(binary, stateDir string) (*collector, error) {
	var lastErr error
	for attempt := range collectorPortAttempts {
		ports, err := reservePorts(3)
		if err != nil {
			return nil, fmt.Errorf("choosing loopback ports: %w", err)
		}

		c, err := launchCollector(binary, stateDir, collectorConfigData{
			OTLPHTTPPort: ports[0],
			OTLPGRPCPort: ports[1],
			HealthPort:   ports[2],
		})
		if err == nil {
			return c, nil
		}
		lastErr = err
		if !errors.Is(err, errCollectorPortTaken) {
			return nil, err
		}
		// A port was taken between reserving and binding. Try again with fresh
		// ones rather than reporting a collision the developer cannot fix.
		_ = attempt
	}
	return nil, fmt.Errorf("could not find free loopback ports after %d attempts: %w",
		collectorPortAttempts, lastErr)
}

// errCollectorPortTaken marks the one failure worth retrying.
var errCollectorPortTaken = errors.New("a chosen loopback port was taken")

func launchCollector(binary, stateDir string, data collectorConfigData) (*collector, error) {
	configPath := filepath.Join(stateDir, collectorConfigFile)
	if err := writeCollectorConfig(configPath, data); err != nil {
		return nil, err
	}

	logPath := filepath.Join(stateDir, collectorLogFile)
	logFile, err := os.OpenFile(logPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, devStateFileMode)
	if err != nil {
		return nil, fmt.Errorf("opening the collector log: %w", err)
	}
	defer logFile.Close()

	cmd := exec.Command(binary, "--config="+configPath)
	cmd.Env = os.Environ()
	cmd.Stdin = nil
	cmd.Stdout = logFile
	cmd.Stderr = logFile
	applyChildProcessAttributes(cmd)

	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("starting %s: %w", filepath.Base(binary), err)
	}

	c := &collector{
		cmd:      cmd,
		httpPort: data.OTLPHTTPPort,
		grpcPort: data.OTLPGRPCPort,
		logPath:  logPath,
		waited:   make(chan error, 1),
	}
	go func() { c.waited <- cmd.Wait() }()

	if err := c.awaitReady(data.HealthPort); err != nil {
		c.stop()
		return nil, err
	}
	return c, nil
}

// awaitReady is the two-step check, and both steps are load-bearing.
//
// /livez proves the Collector is up and that it accepted its configuration — a
// Collector that refused one exits instead. But /livez binding proves only that
// the *health* port bound. The OTLP port is reserved advisorily and can still
// lose its race, and without the second step that failure surfaces much later
// as telemetry that silently went nowhere.
//
// This is the demo prototype's hard-won ordering, adopted rather than
// rediscovered: scripts/tv-dev.sh carries the same two steps with the same
// comment about why one is not enough.
func (c *collector) awaitReady(healthPort int) error {
	deadline := time.Now().Add(collectorReadyTimeout)

	if err := c.pollUntil(deadline, func() bool {
		return probeHealth(healthPort)
	}); err != nil {
		return fmt.Errorf("the OTLP collector never became live: %w\n%s",
			err, tailLog(c.logPath))
	}

	// Both receiver ports, not just the one the environment names: a workload
	// that chose gRPC in code would otherwise start against a port that had lost
	// its race, and the spans would go nowhere with nothing reporting it.
	for _, port := range []int{c.httpPort, c.grpcPort} {
		if err := c.pollUntil(deadline, func() bool { return portAccepts(port) }); err != nil {
			// Distinguished from the first step, because this is the case a bare
			// timeout would hide: live, configured, and not listening for spans.
			return fmt.Errorf("%w: the collector is live but a receiver never "+
				"bound on 127.0.0.1:%d: %w\n%s",
				errCollectorPortTaken, port, err, tailLog(c.logPath))
		}
	}
	return nil
}

// pollUntil waits for a condition, failing early if the process dies.
func (c *collector) pollUntil(deadline time.Time, ready func() bool) error {
	for {
		if ready() {
			return nil
		}
		select {
		case err := <-c.waited:
			// Put it back so stop() can still reap.
			c.waited <- err
			return fmt.Errorf("it exited during startup: %w", err)
		default:
		}
		if time.Now().After(deadline) {
			return fmt.Errorf("timed out after %s", collectorReadyTimeout)
		}
		time.Sleep(collectorPollInterval)
	}
}

// OTLPEndpoint is what the workload's environment exports to.
func (c *collector) OTLPEndpoint() string {
	return fmt.Sprintf("http://127.0.0.1:%d", c.httpPort)
}

// OTLPGRPCEndpoint is the gRPC receiver, for a workload that chose that
// transport in code. Reported in the banner rather than set in the environment:
// OTEL_EXPORTER_OTLP_ENDPOINT carries one endpoint and one protocol.
func (c *collector) OTLPGRPCEndpoint() string {
	return fmt.Sprintf("127.0.0.1:%d", c.grpcPort)
}

// stop shuts the Collector down, gracefully first.
//
// The grace period matters more here than for the control plane: a Collector
// killed mid-batch drops spans, and dropped spans are evidence the run will
// never have. Escalation still exists, because a process that will not exit
// must not hold the developer's shell.
func (c *collector) stop() {
	c.stopOnce.Do(func() {
		if c.cmd == nil || c.cmd.Process == nil {
			return
		}
		forwardSignal(c.cmd.Process, syscall.SIGTERM)

		select {
		case <-c.waited:
			return
		case <-time.After(collectorStopGrace):
		}
		_ = c.cmd.Process.Kill()
		select {
		case <-c.waited:
		case <-time.After(collectorStopGrace):
		}
	})
}

// ---------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------

// writeCollectorConfig renders the document into dev's state directory.
func writeCollectorConfig(path string, data collectorConfigData) error {
	var rendered strings.Builder
	if err := collectorTemplate.Execute(&rendered, data); err != nil {
		return fmt.Errorf("rendering the collector configuration: %w", err)
	}
	if err := os.WriteFile(path, []byte(rendered.String()), devStateFileMode); err != nil {
		return fmt.Errorf("writing the collector configuration: %w", err)
	}
	return nil
}

// validateCollectorScalar refuses a value that cannot go into the document
// safely.
//
// Nothing substitutes a string yet: every value slice 2b writes is a port. It
// exists now because slice 3 substitutes a run id and a behavioral profile —
// caller-supplied strings — and the rule for them should be written while the
// reason is in view rather than discovered by a quoting bug.
//
// The template quotes every string it substitutes, so the rule is the one that
// keeps a *double-quoted* YAML scalar intact: no quote, no backslash, no line
// break, no control character. An earlier version enumerated plain-scalar
// hazards instead and refused every colon — which rejected `git:43af19c`, the
// candidate identity format slice 3 derives from a commit. Quoting the scalar
// and checking a narrow rule is both safer and less surprising than guessing
// which punctuation YAML minds.
//
// Refused, not escaped. These are identity values: a run id rewritten to be
// representable is not the run id the control plane knows, and the Collector
// would then point at a run that does not exist. Task 054 applies the same rule
// to behavioral identity for the same reason.
func validateCollectorScalar(field, value string) error {
	if value == "" {
		return fmt.Errorf("%s is empty", field)
	}
	if strings.TrimSpace(value) != value {
		return fmt.Errorf("%s has leading or trailing whitespace: %q", field, value)
	}
	if strings.ContainsAny(value, "\"\\") {
		return fmt.Errorf(
			"%s contains a quote or backslash, which would break the generated "+
				"configuration: %q", field, value)
	}
	for _, r := range value {
		// Control characters include the line breaks that would let a value
		// introduce a key of its own.
		if r < 0x20 || r == 0x7f {
			return fmt.Errorf(
				"%s contains a control character, which would change the "+
					"structure of the generated configuration: %q", field, value)
		}
	}
	return nil
}

// ---------------------------------------------------------------------
// Ports and probes
// ---------------------------------------------------------------------

// reservePorts picks n distinct free loopback ports.
//
// Every listener is open at once before any port is reported, then all are
// closed. Choosing them one at a time would let a later selection return an
// earlier one's port, because nothing holds it in between — a collision that
// then shows up as "the Collector exited during startup" rather than as itself.
// The demo prototype hit exactly this and allocates in a batch for the same
// reason.
//
// Still advisory: between closing and the Collector binding, another process can
// take one. That is what startCollector's retry is for.
func reservePorts(n int) ([]int, error) {
	listeners := make([]net.Listener, 0, n)
	defer func() {
		for _, listener := range listeners {
			listener.Close()
		}
	}()

	ports := make([]int, 0, n)
	seen := make(map[int]bool, n)
	for range n {
		listener, err := net.Listen("tcp", "127.0.0.1:0")
		if err != nil {
			return nil, err
		}
		listeners = append(listeners, listener)

		port := listener.Addr().(*net.TCPAddr).Port
		if seen[port] {
			// Not reachable while every listener is open, and asserted rather
			// than assumed: two identical ports would make the Collector fight
			// itself for one of them.
			return nil, errors.New("the OS returned one port twice")
		}
		seen[port] = true
		ports = append(ports, port)
	}
	return ports, nil
}

// probeHealth reports whether the processor's /livez answers.
//
// A fresh client per probe with a short timeout, and no keep-alive: this runs a
// few dozen times at startup and never again, so connection reuse would only
// keep a socket open to a process about to be signalled.
func probeHealth(port int) bool {
	client := &http.Client{Timeout: collectorProbeTimeout}
	defer client.CloseIdleConnections()

	url := fmt.Sprintf("http://127.0.0.1:%d/livez", port)
	response, err := client.Get(url)
	if err != nil {
		return false
	}
	defer response.Body.Close()
	return response.StatusCode == http.StatusOK
}

// portAccepts reports whether something is listening.
//
// A dial and an immediate close. Not an OTLP request: sending one would put a
// span into the pipeline that no run asked for, and this only needs to know
// whether the socket exists.
func portAccepts(port int) bool {
	conn, err := net.DialTimeout("tcp",
		fmt.Sprintf("127.0.0.1:%d", port), collectorProbeTimeout)
	if err != nil {
		return false
	}
	conn.Close()
	return true
}
